name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gatsby Publish
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          deploy-branch: gh-pages
