name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.CUCU_AND_CO }}
          deplay-branch: gh-pages
